# Generated by Django 2.2.7 on 2020-07-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payments', '0003_auto_20200620_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PAID', 'PAID'), ('NOT_PAID', 'NOT PAID')], default='NOT_PAID', max_length=50, verbose_name='payment status'),
        ),
    ]
