# Generated by Django 2.2.7 on 2020-10-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('country', models.CharField(max_length=50, verbose_name='country')),
                ('zip_code', models.CharField(blank=True, max_length=50, verbose_name='zip code')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
                ('added_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'location',
                'unique_together': {('address', 'city', 'state')},
            },
        ),
    ]
