# Generated by Django 2.2.7 on 2020-05-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100, verbose_name='address'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('address', 'city', 'state')},
        ),
    ]
