# Generated by Django 2.2.7 on 2020-10-04 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('amount', models.FloatField()),
                ('duration', models.PositiveIntegerField(default=1, verbose_name='duration in days')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('ref_no', models.CharField(default='dfr44f', max_length=50, unique=True, verbose_name='reference number')),
            ],
        ),
        migrations.CreateModel(
            name='SponsoredProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(blank=True, verbose_name='sponsorship will start at')),
                ('status', models.CharField(choices=[('PROCESSING', 'processing'), ('SUCCESSFUL', 'process successful'), ('FAILED', 'process failed')], default='PROCESSING', max_length=50, verbose_name='status')),
                ('ref_no', models.CharField(default='dfr44f', max_length=50, unique=True, verbose_name='reference number')),
            ],
            options={
                'verbose_name': 'sponsored_product',
                'verbose_name_plural': 'sponsored_products',
                'db_table': 'sponsored_product',
                'ordering': ['-start_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SponsoredStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(blank=True, verbose_name='sponsorship will start at')),
                ('status', models.CharField(choices=[('PROCESSING', 'processing'), ('SUCCESSFUL', 'process successful'), ('FAILED', 'process failed')], default='PROCESSING', max_length=50, verbose_name='status')),
                ('ref_no', models.CharField(default='dfr44f', max_length=50, unique=True, verbose_name='reference number')),
                ('payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_sponsoredstore_related', to='Payments.Payment')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_sponsoredstore_related', to='Sponsored.AdsPlan')),
            ],
            options={
                'verbose_name': 'sponsored_store',
                'verbose_name_plural': 'sponsored_stores',
                'db_table': 'sponsored_store',
                'ordering': ['-start_at'],
                'abstract': False,
            },
        ),
    ]
