# Generated by Django 2.2.7 on 2020-06-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsored', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoredproduct',
            name='start_at',
            field=models.DateTimeField(blank=True, verbose_name='sponsorship will start at'),
        ),
        migrations.AlterField(
            model_name='sponsoredstore',
            name='start_at',
            field=models.DateTimeField(blank=True, verbose_name='sponsorship will start at'),
        ),
    ]
