# Generated by Django 2.2.7 on 2020-10-04 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stores', '0001_initial'),
        ('Payments', '0001_initial'),
        ('Products', '0002_auto_20201004_2348'),
        ('Sponsored', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoredstore',
            name='store',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Stores.Store'),
        ),
        migrations.AddField(
            model_name='sponsoredproduct',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_sponsoredproduct_related', to='Payments.Payment'),
        ),
        migrations.AddField(
            model_name='sponsoredproduct',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_sponsoredproduct_related', to='Sponsored.AdsPlan'),
        ),
        migrations.AddField(
            model_name='sponsoredproduct',
            name='product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Product'),
        ),
    ]
