# Generated by Django 2.2.7 on 2020-06-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sponsored', '0002_auto_20200611_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsplan',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
