# Generated by Django 2.2.7 on 2020-05-04 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stores', '0001_initial'),
        ('Ratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreRating',
            fields=[
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, null=True, verbose_name='total rating average')),
                ('n_one_star_votes', models.PositiveIntegerField(default=0, null=True, verbose_name='number of 1 star ratings')),
                ('n_two_stars_votes', models.PositiveIntegerField(default=0, null=True, verbose_name='number of 2 star ratings')),
                ('n_three_stars_votes', models.PositiveIntegerField(default=0, null=True, verbose_name='number of 3 star ratings')),
                ('n_four_stars_votes', models.PositiveIntegerField(default=0, null=True, verbose_name='number of 4 star ratings')),
                ('n_five_stars_votes', models.PositiveIntegerField(default=0, null=True, verbose_name='number of 5 star ratings')),
                ('n_votes', models.PositiveIntegerField(default=0, null=True, verbose_name='number of votes')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rating', serialize=False, to='Stores.Store', verbose_name='store')),
            ],
            options={
                'db_table': 'store_ratings',
                'ordering': ['-average_rating'],
                'abstract': False,
            },
        ),
    ]
