# Generated by Django 2.2.7 on 2020-08-11 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ref_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='reference number'),
        ),
    ]
