# Generated by Django 2.2.7 on 2020-08-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_category_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='ref_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='reference number'),
        ),
    ]
