# Generated by Django 2.2.7 on 2020-10-04 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stores', '0001_initial'),
        ('Users', '0001_initial'),
        ('Buyer', '0001_initial'),
        ('Products', '0002_auto_20201004_2348'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.Address'),
        ),
        migrations.AddField(
            model_name='shipping',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_details', to='Buyer.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='items_viewed',
            field=models.ManyToManyField(blank=True, related_name='users_viewed', to='Products.Product'),
        ),
        migrations.AddField(
            model_name='profile',
            name='stores_followed',
            field=models.ManyToManyField(blank=True, related_name='users_following', to='Stores.Store'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='buyer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='wish_list',
            field=models.ManyToManyField(blank=True, related_name='users_wishlist', to='Products.Product'),
        ),
    ]
