# Generated by Django 2.2.7 on 2020-10-04 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'product_review',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'store_review',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductReviewResponse',
            fields=[
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='response', serialize=False, to='Reviews.ProductReview', verbose_name='review')),
                ('response', models.TextField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'product_review_responses',
            },
        ),
        migrations.CreateModel(
            name='StoreResponse',
            fields=[
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='response', serialize=False, to='Reviews.StoreReview', verbose_name='review')),
                ('response', models.TextField(blank=True, default='', max_length=300)),
            ],
            options={
                'db_table': 'store_review_response',
            },
        ),
    ]
