# Generated by Django 2.2.7 on 2020-05-04 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0002_auto_20200504_2006'),
        ('Reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_storereview_related', to=settings.AUTH_USER_MODEL, verbose_name='buyer'),
        ),
        migrations.AddField(
            model_name='storereview',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Stores.Store', verbose_name='store'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_productreview_related', to=settings.AUTH_USER_MODEL, verbose_name='buyer'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Products.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='storeresponse',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_review_responses', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='productreviewresponse',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review_responses', to=settings.AUTH_USER_MODEL, verbose_name='seller'),
        ),
    ]
