# Generated by Django 2.2.7 on 2020-05-04 19:06

import Adverts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(blank=True, upload_to=Adverts.models.upload_to)),
                ('text', models.TextField(blank=True, max_length=100, verbose_name='advert text')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'advert',
                'verbose_name_plural': 'adverts',
                'db_table': 'store_adverts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
