# Generated by Django 2.2.7 on 2020-05-04 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adverts', '0001_initial'),
        ('Stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Stores.Store', verbose_name='store'),
        ),
    ]
