# Generated by Django 2.2.7 on 2020-05-04 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('Cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Products.Product', verbose_name='products'),
        ),
        migrations.AddField(
            model_name='cart',
            name='variants',
            field=models.ManyToManyField(to='Products.Variation', verbose_name='variant of product'),
        ),
    ]
