# Generated by Django 2.2.7 on 2020-05-04 19:06

import Stores.models.store
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to=Stores.models.store.upload_to)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='store name')),
                ('ref_no', models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='reference no')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
