# Generated by Django 2.2.7 on 2020-10-04 22:48

import Stores.models.advert
import Stores.models.store
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(blank=True, upload_to=Stores.models.advert.ad_upload_to)),
                ('text', models.TextField(blank=True, max_length=100, verbose_name='advert text')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'advert',
                'verbose_name_plural': 'adverts',
                'db_table': 'store_advert',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to=Stores.models.store.upload_to)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='store name')),
                ('ref_no', models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='reference no')),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'store',
            },
        ),
    ]
