# Generated by Django 2.2.7 on 2020-06-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0002_auto_20200504_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
