# Generated by Django 2.2.7 on 2020-06-21 21:09

import Stores.models.store
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stores', '0003_store_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ImageField(blank=True, upload_to=Stores.models.store.ad_upload_to)),
                ('text', models.TextField(blank=True, max_length=100, verbose_name='advert text')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Stores.Store', verbose_name='store')),
            ],
            options={
                'verbose_name': 'advert',
                'verbose_name_plural': 'adverts',
                'db_table': 'store_adverts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
