# Generated by Django 2.2.7 on 2020-07-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0002_auto_20200504_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('PICKUP_SITE', 'Pick-up sites'), ('DOOR_2_DOOR', 'Door-to-Door delivery')], default='DOOR_2_DOOR', max_length=50, verbose_name='delivery method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ENROUTE', 'Enroute'), ('PROCESSING', 'Processing'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PROCESSING', max_length=50, verbose_name='order status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('GRANTED', 'Granted'), ('NO_REQUEST', 'No Request')], default='REQUESTED', max_length=50, verbose_name='refund status'),
        ),
    ]
