# Generated by Django 2.2.7 on 2020-10-04 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stores', '0001_initial'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Stores.Store'),
        ),
        migrations.AddField(
            model_name='keyfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_features', to='Products.Product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='Products.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='variation',
            unique_together={('attribute', 'vendor_metric')},
        ),
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together={('product', 'type', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='keyfeature',
            unique_together={('product', 'feature')},
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('product', 'name')},
        ),
    ]
